### ISSUE TITLE
Disable Vanity 

### ISSUE THREAD

**Issue by Erduan87** [amitt001/pygmy#26]
I have a question. Can I disable vanity in Pygmy (I want a random hash = www.expamle.com/**abc123**). If it is possible, how can I disable it?

**Comment by amitt001** [comment]
@Erduan87 do you want the custom domain(like example.com?) or a prefixed url path(like exmaple.com/abc**)?

You can use your own custom domain in the service. Customize your config and settings file to add your domain. 

About the path in url(In your example **abc123**) can only be an ever-increasing base62 encoded value.

**Comment by amitt001** [comment]
@Erduan87 ^^
