### ISSUE TITLE
Secure the homepage to prevent access from outside

### ISSUE THREAD

**Issue by lukaalba** [amitt001/pygmy#28]
Hi,
I don't want people from outside of my network using the url shortener to create own short urls. 
Is it possible to secure the mainpage AND make the urls for everyone available?

**Comment by amitt001** [comment]
@lukaalba apologise for not getting back to you quicker. 

There a couple of ways to achieve this. Listing some here

1. IP whitelist on url patterns(like <domain>/shorten/*) through nginx. A google search returned this https://stackoverflow.com/questions/13917866/nginx-ip-whitelist
2. Prevent public access to all the URLs except https://<domain>/<code> and only allow GET request through nginx
3. Only allow the logged-in user to create shortened URL and disable register option from the main page (Simple and clean)

I prefer 3rd :)
