### ISSUE TITLE
Feature Request - Simplified Flask Implementation

### ISSUE THREAD

**Issue by caffeinatedMike** [amitt001/pygmy#33]
This is very impressive!

This is the exact tool I've been looking for with the two features I wanted most: link click stats & link expiration. 

Is there anyway someone would be willing to convert this repo into a simplified flask-implementation? My entire setup for a project I'm working on is built on the flask framework and I was looking to have a custom link shortener with

1. The option to have a link expire after a set amount of time (say you send a link to a customer for an invoice, they would only have access to the link for 72 hours or so at which point the invoice is no longer valid).
2. The option to just track link clicks. I'm not worried about location really.
  - This feature would be great for the above mentioned invoice situation to see if the client has opened the invoice
  - It could also be beneficial for email campaigns to know which customers showed interest in particular services or deals. That would allow for potential Lead generation to more accurately target potential upsell opportunities.

**Comment by amitt001** [comment]
Hello @caffeinatedMike, I didn't get what do you mean a by "simplified flask-implementation".

This project is already implemented in flask with frontend(UI serving engine) written in Django. You can keep using the flask-based API and just write your own frontend on top of that API. You can get rid of this Django part https://github.com/amitt001/pygmy/tree/master/pygmyui

**Comment by caffeinatedMike** [comment]
Oh my God, I'm so sorry. I was viewing it via the Android app and hadn't realized the ui code was entirely separate at first glance. Now I see the divide. Again, sorry about that! 

Amazing work btw, thank you for creating this 😊
